_format_version: "1.1"
_transform: true

services:
- host: mockbin.org
  name: example_service
  port: 80
  protocol: http
  routes:
  - name: example_route
    paths:
    - /mock
    strip_path: true
- host: localhost
  name: backend
  port: 39090
  protocol: http
  routes:
  - name: backend_route
    paths:
    - /backend
    strip_path: true