type: Dataplane
mesh: default
name: backend
networking:
  address: {{ address }}
  inbound: 
  - port: 19090
    servicePort: 9090
    serviceAddress: 127.0.0.1
    tags:
      kuma.io/service: backend