type: Dataplane
mesh: default
name: api
networking:
  address: {{ address }}
  inbound: 
  - port: 19090
    servicePort: 9090
    serviceAddress: 127.0.0.1
    tags:
      kuma.io/service: api
  outbound:
  - port: 39091
    tags:
      kuma.io/service: database