type: Dataplane
mesh: default
name: payments
networking:
  address: {{ address }}
  inbound: 
  - port: 29090
    servicePort: 9091
    serviceAddress: 127.0.0.1
    tags:
      kuma.io/service: payments
